image: node:13.13

cache:
  paths:
    - node_modules/

before_script:
  - npm install

#test:
#  stage: test
#  script:
#    - CI=true npm test
#  only:
#    - master

pages:
  stage: deploy
  script:
    - CI=true npm build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
#  only:
#    - master
